version: '1.0'

tasks:
  cleanup:
    description: "Clean up temporary files and directories"
    runs:
      - name: Remove Python bytecode files
        run: |
          find . -name '*.pyc' -delete
          find . -name '*.pyo' -delete
          find . -name '*.pyd' -delete
          find . -name '__pycache__' -type d -exec rm -r {} +

      - name: Remove build and distribution directories
        run: |
          rm -rf build/
          rm -rf dist/
          rm -rf *.egg-info
          
      - name: Remove test and coverage reports
        run: |
          rm -f .coverage
          rm -f *.cover
          rm -f coverage.xml
          rm -f nosetests.xml

  lint:
    description: "Lint the code with flake8"
    runs:
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 .

  run_tests:
    description: "Run unit tests with nose"
    runs:
      - name: Install nose
        run: |
          python -m pip install --upgrade pip
          pip install nose

      - name: Run unit tests
        run: |
          nosetests